Update buildsolution.yml

diff --git a/.github/workflows/buildsolution.yml b/.github/workflows/buildsolution.yml
--- a/.github/workflows/buildsolution.yml
+++ b/.github/workflows/buildsolution.yml
@@ -33,6 +33,14 @@ jobs:
         with:
           path: '\\mspfedyn_\\OrgDbOrgSettings\\Solution\\WebResources\\mspfedyn_\\OrgDbOrgSettings\\'
           file-endings: '.xml'
+      - name: Check for Unescaped Characters in the validated xml files
+        run: |
+          if grep -q '<[^<]*[^&lt;]' 'mspfedyn_/OrgDbOrgSettings/Solution/WebResources/mspfedyn_/OrgDbOrgSettings/settings.xml'; then
+            echo "Error: Unescaped characters detected in XML files."
+            exit 1
+          else
+            echo "No unescaped characters found."
+          fi
       - name: apply updated version
         run: | 
           #edit settings.xml build number 
